create table usr (
    id int8 generated by default as identity,
    email varchar(255),
    password varchar(255) not null,
    username varchar(255) not null,
    primary key (id)
);

create table roles(
	id int not null,
	name varchar(255) not null,
	primary key (id)
);

create table user_role (
    user_id int8 not null,
    role_id int not null
);

create table movie (
    id int8 generated by default as identity,
    title varchar(255),
    genre varchar(255),
    details varchar(600),
    release_date date,
    score float(4),
    primary key (id)
);

create table favourite_genre(
      user_id int8 generated by default as identity,
	genre varchar(255),
	primary key (user_id)

);


create table User_review (
    review_id int8 generated by default as identity,
    user_id int8 not null,
    primary key (review_id )

);

create table review (
    id int8 generated by default as identity,
    review_id int8 not null,
    movie_id int8 not null,
    message varchar(255),
    primary key (id)
    );

create table User_Voting (
    voting_id int8 generated by default as identity,
    user_id int8 not null,
    primary key (voting_id)
    );

create table Voting (
    id int8 generated by default as identity,
    voting_id int8 not null,
    movie_id int8 not null,
    vote int,
    primary key (id)
);


alter table if exists favourite_genre
    add constraint UK_gp5u9cs9leiwnbh2rhn27e2w7
    foreign key (user_id) references usr;

alter table if exists User_review 
    add constraint FK7ncuqw9n77odylknbo8aikc9w
    foreign key (user_id) references usr;

alter table if exists review
    add constraint FK8jft4d30d5dgvauht7ssndwau
    foreign key (movie_id ) references movie;
alter table if exists review
    add constraint FKi6hpa14qaenek8pc9pf3vmlei
    foreign key (review_id) references User_review;
	
alter table if exists User_Voting 
    add constraint FKq51iuslnvq3nw8teocq9y7ag8
    foreign key (user_id) references usr;

alter table if exists Voting
    add constraint FKfpm8swft53ulq2hl11yplpr5
    foreign key (movie_id ) references movie;
alter table if exists Voting
    add constraint FK7k3k0ru1omu7xdtdamtrl276
    foreign key (vote_id)references User_Voting;


insert into roles values(1,'ROLE_USER');
insert into roles values(2,'ROLE_MODERATOR');
insert into roles values(3,'ROLE_ADMIN');

insert into movie (title,genre,details,release_date,score)values('The King''s Man','Action','In the early years of the 20th century, the Kingsman agency is formed to stand against a cabal plotting a war to wipe out millions.', DATE'2022-01-14',0);
insert into movie (title,genre,details,release_date,score)values('Licorice Pizza','Comedy','The story of Alana Kane and Gary Valentine growing up, running around and going through the treacherous navigation of first love in the San Fernando Valley, 1973.', DATE'2021-11-26',0);
insert into movie (title,genre,details,release_date,score)values('Texas Chainsaw Massacre','Horror','After nearly 50 years of hiding, Leatherface returns to terrorize a group of idealistic young friends who accidentally disrupt his carefully shielded world in a remote Texas town.', DATE'2022-02-18',0);
insert into movie (title,genre,details,release_date,score)values('Spider-Man: No Way Home','Fantasy','With Spider-Man''s identity now revealed, Peter asks Doctor Strange for help. When a spell goes wrong, dangerous foes from other worlds start to appear, forcing Peter to discover what it truly means to be Spider-Man.', DATE'2021-12-17',0);
insert into movie (title,genre,details,release_date,score)values('Marry Me','Romance','Music superstars Kat Valdez and Bastian are getting married before a global audience of fans. But when Kat learns, seconds before her vows, that Bastian has been unfaithful, she instead decides to marry Charlie, a stranger in the crowd.', DATE'2022-02-11',0);
insert into movie (title,genre,details,release_date,score)values('The Dark Knight','Thriller','When the menace known as the Joker wreaks havoc and chaos on the people of Gotham, Batman must accept one of the greatest psychological and physical tests of his ability to fight injustice.', DATE'2008-07-18',0);
insert into movie (title,genre,details,release_date,score)values('The Batman','Drama','When the Riddler, a sadistic serial killer, begins murdering key political figures in Gotham, Batman is forced to investigate the city''s hidden corruption and question his family''s involvement.', DATE'2022-03-04',0);
insert into movie (title,genre,details,release_date,score)values('Encanto','Fantasy','A Colombian teenage girl has to face the frustration of being the only member of her family without magical powers.', DATE'2021-11-24',0);
insert into movie (title,genre,details,release_date,score)values('Inception','Thriller','A thief who steals corporate secrets through the use of dream-sharing technology is given the inverse task of planting an idea into the mind of a C.E.O., but his tragic past may doom the project and his team to disaster.', DATE'20010-07-16',0);
insert into movie (title,genre,details,release_date,score)values('Licorice Pizza','Comedy','The story of Alana Kane and Gary Valentine growing up, running around and going through the treacherous navigation of first love in the San Fernando Valley, 1973.', DATE'2021-11-26',0);
insert into movie (title,genre,details,release_date,score)values('Scream','Horror','Twenty-five years after the original series of murders in Woodsboro, a new Ghostface emerges, and Sidney Prescott must return to uncover the truth.', DATE'2022-01-14',0);
insert into movie (title,genre,details,release_date,score)values('The French Dispatch','Romance','A love letter to journalists set in an outpost of an American newspaper in a fictional twentieth century French city that brings to life a collection of stories published in "The French Dispatch Magazine".', DATE'2021-08-22',0);
insert into movie (title,genre,details,release_date,score)values('Free Guy','Fantasy','A bank teller discovers that he''s actually an NPC inside a brutal, open world video game.', DATE'2021-07-13',0);
insert into movie (title,genre,details,release_date,score)values('Death on the Nile','Drama','While on vacation on the Nile, Hercule Poirot must investigate the murder of a young heiress.', DATE'2022-02-11',0);

insert into movie (title,genre,details,release_date,score)values('Doctor Strange in the Multiverse of Madness','Fantasy','Dr. Stephen Strange casts a forbidden spell that opens the door to the multiverse, including an alternate version of himself, whose threat to humanity is too great for the combined forces of Strange, Wong, and Wanda Maximoff.', DATE'2022-05-06',0);